apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector: 
    matchLabels:
      deployment: kafka-ui
  template:
    metadata:
      labels:
        deployment: kafka-ui
    spec:
      containers:
          - name: kafka-ui
            image: provectuslabs/kafka-ui:latest
            ports:
              - containerPort: 8080
            env:
              - name: KAFKA_CLUSTERS_0_NAME
                value: "kafka-data-dev"
              - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
                value: "kafka-0.kafka-svc.kafka.svc.cluster.local:9092,kafka-1.kafka-svc.kafka.svc.cluster.local:9092,kafka-2.kafka-svc.kafka.svc.cluster.local:9092"